### ISSUE TITLE
Sidebar becomes narrower

### ISSUE THREAD

**Issue by artemith** [yoyurec/logseq-awesome-ui#6] opened 2022-10-14 09:37 UTC
**Info:**
- OS: Windows 10 21H2
- Logseq ver: 0.8.8+nightly20221010
- Theme ver: Awesome UI 1.2.10
- [√] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
A clear and concise description of what the bug is......
The main page and sidebar while opening the page with metadata (like zotero imported page), and then open the PDF, the sidebar will become particularly narrow, can not read. The sidebar cannot be wider. 

After closing Awesome UI, the width of sidebar becomes normal.

**To Reproduce:**
 ...
1. Open a page with metadata
2. Open a page with metadata in sidebar
3. Open a PDF
4. The sidebar becomes narrower.
5. Close Awesome UI, the width of sidebar becomes normal

**Expected behavior:**
 ...
The width of sidebar should not be changed

**Screenshots**
The interference **without** Awesome UI
![Snipaste_2022-10-14_17-25-05](https://user-images.githubusercontent.com/14881525/195814090-668ebd1f-79e3-4bfc-94ff-2cb0d4d19dd3.png)

This is the interference **with** Awesome UI, the width of sidebar changes, can not read.
![Snipaste_2022-10-14_17-25-49](https://user-images.githubusercontent.com/14881525/195814269-4185cb1b-fc25-4798-b2dd-feecad4e434b.png)

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment] 2022-10-15 22:19
trying to reproduce - Win10, Logseq : 0.8.8, disabled AwesomeUI, default theme

when i open PDF both content & right sidebar became smaller.
same as with enabled AwesomeUI.... see no difference. plus in both cases sidebar can be resized via dragging.

maybe you can record loom video to demonstrate more difference detailed - init sizes, changes after opening pdf?

**Comment by artemith** [comment] 2022-10-16 00:27
> trying to reproduce - Win10, Logseq : 0.8.8, disabled AwesomeUI, default theme
> 
> when i open PDF both content & right sidebar became smaller. same as with enabled AwesomeUI.... see no difference. plus in both cases sidebar can be resized via dragging.
> 
> maybe you can record loom video to demonstrate more difference detailed - init sizes, changes after opening pdf?

Here is the screen video
https://1drv.ms/v/s!Ahii9UG-C9skko8aGBS1uUGmFOzORA?e=trdtcF

Here is the test file
[@Monetary policy uncertainty.md](https://github.com/yoyurec/logseq-awesome-ui/files/9793359/%40Monetary.policy.uncertainty.md)
[Chang_等。_-_2017_-_Pre-market_Trading_and_IPO_Pricing_1665496255521_0.pdf](https://github.com/yoyurec/logseq-awesome-ui/files/9793360/Chang_._-_2017_-_Pre-market_Trading_and_IPO_Pricing_1665496255521_0.pdf)

In 0.8.2, the problem does not exist. After I update my Logseq to 0.8.8+nightly20221010, it happened.

**Comment by yoyurec** [comment] 2022-10-16 00:36
thnx for detailed info! will check locally

"0.8.8+nightly" ? what does it mean?
there are 2 branches - stable or dev
**0.8.8** or **nightly**
or or...

i do not support (cose it's impossible) nightly till release.... so you need to wait some time for Logseq team
BTW in nigtly dev build a lot of HTML changed and few issues in plugins spotted

**Comment by yoyurec** [comment] 2022-10-16 00:48
![image](https://user-images.githubusercontent.com/137919/196012622-3f0d11af-a5ab-4dfe-9623-20d601504196.png)

looks like it's bcose of long URL text in props has `nowrap` and stops content shrinking (=sidebar growing) on resize.
will fix soon, just working right now on page props block new cool design )

**Comment by artemith** [comment] 2022-10-16 01:30
Thank you！

**Comment by artemith** [comment] 2022-10-20 01:41
When press "t + w" to open wide mode, the sidebar becomes narrower

**Comment by yoyurec** [comment] 2022-10-20 03:10
try to disable AwesomeUI if you have it - issue gone?

**Comment by yoyurec** [comment] 2022-10-20 03:11
it will be fixed too -same issue

**Comment by yoyurec** [comment] 2022-10-21 19:16
fixed

**Closed as completed by yoyurec** 2022-10-21 19:16 UTC
Labels: bug
