### ISSUE TITLE
edit icon display incorrectly and request a setting to hide this icon

### ISSUE THREAD

**Issue by fortunehan** [yoyurec/logseq-awesome-ui#19] opened 2022-10-28 14:48 UTC
**Info:**
- OS: macOS Monterey
- Logseq ver: 0.8.9
- Plugin ver: 1.3.10
- Theme name: Awesome Styler Dark

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
The edit icon doesn't display correct in some scenarios

Hi @yoyurec,

Could I seek your help to check?

**To Reproduce:**
1.  Enter new line to add new property.
2. Enter new line in src.

**Expected behavior:**
1. have a setting config to **hide** the edit icon
2. display edit icon correctly

**Screenshots**
<img width="356" alt="Xnip2022-10-28_22-39-42" src="https://user-images.githubusercontent.com/9983619/198656173-8474d531-3687-4f83-bc2f-b5e4671590ea.png">

<img width="58" alt="Xnip2022-10-28_22-41-22" src="https://user-images.githubusercontent.com/9983619/198656112-47456256-2121-43f1-9017-3b3146bb81a7.png">

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment] 2022-10-28 15:13
* have you changed font size? edit icon was done very hacky as repeated background and can be showed with issues ((
* can you post dummy text from 2nd screen to reproduce?

**Comment by fortunehan** [comment] 2022-10-29 04:43
Please check my settings.
and just add a empty `src` can reproduce this issue.
<img width="266" alt="Xnip2022-10-29_12-40-47" src="https://user-images.githubusercontent.com/9983619/198814290-f7a635ea-7e3f-4bc6-87ed-2babd55f2779.png">
<img width="559" alt="Xnip2022-10-29_12-40-21" src="https://user-images.githubusercontent.com/9983619/198814293-73743dd0-cd8f-44a2-be61-72c7545ffd54.png">

And after add the edit icon, the space is a little big, it is not very easy to see whether it is child indent or not from my feeling.
But the styled props feature is really awesome!

<img width="234" alt="Xnip2022-10-29_12-47-13" src="https://user-images.githubusercontent.com/9983619/198814434-c366b97c-6023-4d59-9dea-420f056e87db.png">

**Comment by yoyurec** [comment] 2022-10-29 05:26
hm... looks like Logseq think this bock is page/block props (adding special class) - i'm just styling it. so it's not plugin bug, but became visible b'cose of plugin ))

need to think what to do or wait next app release hoping it will be fixed

**Comment by yoyurec** [comment] 2022-10-29 05:31
> And after add the edit icon, the space is a little big

place not big - place equal to "view" mode. so when you click to edit, prop key text does not jump, but just icons changes...

![ezgif com-gif-maker](https://user-images.githubusercontent.com/137919/198815601-f97b7183-a61b-4ac8-b16e-618ef5ec16f0.gif)

**Comment by yoyurec** [comment] 2022-10-29 05:33
again - showing "edit" icon for every line of simple text blocks is not a feature, it's a bug.
can you attach /paste the content of the buggy **.md** file?

**Comment by yoyurec** [comment] 2022-10-29 05:35
BTW, whay are you adding code ` ``` ... ``` ` to props? 🤔

**Comment by fortunehan** [comment] 2022-10-30 08:36
I got it. This is caused by my habit of taking notes.
I take content notes nested as the child of page properties.
So when I query some tags of page, all its content can be referenced and linked. This is the way I taking notes.

And why the space between property key and value is too big in my side?

<img width="572" alt="Xnip2022-10-30_16-22-42" src="https://user-images.githubusercontent.com/9983619/198869255-8ec8c726-1fae-4ed6-bd2e-428766d3883b.png">

**Comment by yoyurec** [comment] 2022-10-30 11:44
>And why the space between property key and value is too big in my side?

hm. it shouldn't be. can you post cont of file here as code?
```md
...
```

**Comment by fortunehan** [comment] 2022-10-30 14:56
```
date:: [[Oct 30th, 2022]]

	- test
	- ``` 
	  
	  ```
```

**Closed as completed** 2022-10-31 19:59 UTC
Labels: released

**Comment by yoyurec** [comment] 2022-10-31 20:02
@fortunehan check latest release!

**Comment by fortunehan** [comment] 2022-11-03 13:15
Thanks! It works perfectly!
