### ISSUE TITLE
Clashes with Tabs plugin. 

### ISSUE THREAD

**Issue by hiltronrex** [yoyurec/logseq-awesome-ui#17] opened 2022-10-25 22:08 UTC
When you have Awesome UI and Tabs enabled you can't drag the window about so you have to pick between either. It would be nice if they worked together. 

https://github.com/pengx17/logseq-plugin-tabs

**Comment by rben01** [comment] 2022-10-26 03:19
Also seeing this bug. Having the two plugins enabled simultaneously doesn't always disable dragging the window — it's somewhat intermittent. And when it does happen I think it's enough to just close and reopen the window to fix the issue.

**Comment by rben01** [comment] 2022-10-26 03:40
A few notes:

- It seems to be caused by clicking the "Close All" button in the tab bar
- It can be fixed by resizing the window

**Comment by yoyurec** [comment] 2022-10-26 11:27
actually, the whole tabs panel is draggable via `-webkit-app-region: drag;`
![image](https://user-images.githubusercontent.com/137919/198013825-d1a82d4f-453d-4009-bba8-0e1aa31bd4b2.png)

can you provide more info? why you have not used the issue template? its prepared for to make life easier and save time.

![image](https://user-images.githubusercontent.com/137919/198014304-9604286a-ba5d-4b13-930f-e41315373b27.png)

**Comment by hiltronrex** [comment] 2022-10-26 18:54
Its supposed to be but doesn't work until you resize the window as someone else said

**Comment by yoyurec** [comment] 2022-10-26 19:17
no info = no ideas

**Comment by yoyurec** [comment] 2022-10-27 11:32
Mac. it was Mac. 🧐

**Comment by yoyurec** [comment] 2022-10-27 11:34
https://github.com/pengx17/logseq-plugin-tabs/pull/63
should be fixed

**Closed as completed** 2022-10-27 14:05 UTC
